[flyway]
environment = "local"
locations = ["filesystem:migrations"]
defaultSchema = "public"
cleanDisabled = true
validateMigrationNaming = true
[environments.local]
url = "jdbc:postgresql://db:5432/metro"
user = "metro"
password = "${FLYWAY_PASSWORD}"
schemas = ["public"]
